/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Server.ClientHandler;
import Server.Server;
import java.awt.Color;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class ServerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ServerGUI
     */
    private Server server;
    private boolean status = false;
    private String ip;
    private int port;
    public ServerGUI(Server server) {
        this.server = server;
        if (server.getServerSocket()!=null){
            initComponents();
            launchServer(); 
        }           
    }
    private void launchServer(){
        server.setList(onlineList);
        server.setLog(logArea);
        logArea.append("Server is initializing...\n");
        new Thread(() -> {
            server.listen();
        }).start();
        status = true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        onlineScroll = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList<>();
        logScroll = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        hostLabel = new javax.swing.JLabel();
        switchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        portLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        portLabel.setForeground(new java.awt.Color(255, 0, 0));
        portLabel.setText("PORT: " + server.getServerSocket().getLocalPort());
        portLabel.setForeground(Color.RED);

        jLabel1.setText("Online users:");

        onlineScroll.setRowHeaderView(null);
        onlineScroll.setViewportView(onlineList);

        onlineList.setModel(new DefaultListModel<>());
        onlineList.setFixedCellHeight(40);
        onlineScroll.setViewportView(onlineList);

        logArea.setEditable(false);
        logArea.setColumns(20);
        logArea.setLineWrap(true);
        logArea.setRows(5);
        logScroll.setViewportView(logArea);

        jLabel2.setText("Log:");

        hostLabel.setFont(new java.awt.Font("sansserif", 0, 16));
        hostLabel.setForeground(new java.awt.Color(255, 0, 0));
        hostLabel.setText("Host: " + server.getServerSocket().getInetAddress().getHostAddress());

        switchBtn.setText("On/Off");
        switchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(onlineScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(switchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostLabel)
                    .addComponent(switchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logScroll)
                    .addComponent(onlineScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void switchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchBtnActionPerformed
        // TODO add your handling code here:
        if (status){
            try {
                port = server.getServerSocket().getLocalPort();
                ip = server.getServerSocket().getInetAddress().getHostAddress();
                for (ClientHandler client : server.getClients().values()){
                    client.notifyDisconnection();
                }
                server.getServerSocket().close();
                logArea.append("Server disconnected!!\n");
                status = false;
            } catch (IOException ex) {
            }
        }else{
            server = new Server(ip,port);
            status = true;
            launchServer();
        }
    }//GEN-LAST:event_switchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hostLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea logArea;
    private javax.swing.JScrollPane logScroll;
    private javax.swing.JList<String> onlineList;
    private javax.swing.JScrollPane onlineScroll;
    private javax.swing.JLabel portLabel;
    private javax.swing.JButton switchBtn;
    // End of variables declaration//GEN-END:variables

}
